name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: ["dylan", "chris"]

    steps:
      - uses: actions/checkout@v2
      - name: Build for env ${{ matrix.env }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build --if-present
